// Code generated by go generate; DO NOT EDIT.
// This file was generated at: 2020-12-29 15:57:48.176323681 -0800 PST m=+0.000545607
// This file is in sync with: ffb93a3f9d7d7153c52b48a4a7b466b6e95eb805
package cmd

import (
	"fmt"
	"runtime"

	"github.com/AlbinoGeek/sc2-rsu/sc2replaystats"
)

// PROGRAM is the human readable product name
const PROGRAM = "sc2-rsu"

// VERSION is the human readable product version
const VERSION = "v0.4-3-gffb93a3"

func init() {
	sc2replaystats.ClientIdentifier = fmt.Sprintf("%s-%s", PROGRAM, runtime.GOOS)
}
