// Code generated by go generate; DO NOT EDIT.
// This file was generated at: 2020-12-24 15:20:10.887739073 -0800 PST m=+0.001007008
// This file is in sync with: 3bc0f3b1116c42d08371d130d01ba2e965b271c9
package cmd

import (
	"fmt"
	"runtime"

	"github.com/AlbinoGeek/sc2-rsu/sc2replaystats"
)

// PROGRAM is the human readable product name
const PROGRAM = "sc2-rsu"

// VERSION is the human readable product version
const VERSION = "v0.3-78-g7d97f9a"

func init() {
	sc2replaystats.ClientIdentifier = fmt.Sprintf("%s-%s", PROGRAM, runtime.GOOS)
}
