// Code generated by go generate; DO NOT EDIT.
// This file was generated at: 2020-12-24 12:29:12.6009687 -0800 PST m=+0.000806487
// This file is in sync with: 3bc0f3b1116c42d08371d130d01ba2e965b271c9
package cmd

import (
	"fmt"
	"runtime"

	"github.com/AlbinoGeek/sc2-rsu/sc2replaystats"
)

// PROGRAM is the human readable product name
const PROGRAM = "sc2-rsu"

// VERSION is the human readable product version
const VERSION = "v0.3-74-g3bc0f3b"

func init() {
	sc2replaystats.ClientIdentifier = fmt.Sprintf("%s-%s", PROGRAM, runtime.GOOS)
}
